version: 2.1
jobs:
  build:
    docker:
      - image: ocrd/core
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y openjdk-8-jdk-headless wget git gcc unzip ssh
      - checkout
      - run: git submodule update --init
      - run: sudo make test

  deploy-docker:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker: # https://circleci.com/docs/2.0/building-docker-images/
          docker_layer_caching: true
      - run: make docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USER" --password-stdin
      - run: docker push ocrd/fileformat

workflows:
  version: 2
  build-master:
    jobs:
      - build
  deploy:
    jobs:
      - deploy-docker:
          filters:
            branches:
              only: master
