version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get install -y openjdk-11-jdk-headless wget git gcc unzip
      - run: sudo make install-fileformat install PREFIX=/usr/local
      - run: make docker

workflows:
  version: 2
  build-master:
    jobs:
      - build
