version: 2.1
jobs:
  build:
    docker:
      - image: ocrd/core
    steps:
      - checkout
      - run: git submodule update --init
      - run: sudo apt-get install -y openjdk-8-jdk-headless wget git gcc unzip
      - run: sudo make install-fileformat install PREFIX=/usr/local
      # - run: make docker

workflows:
  version: 2
  build-master:
    jobs:
      - build
