version: 2.1
jobs:
  build:
    docker:
      - image: ocrd/core
    steps:
      - run: sudo apt-get install -y openjdk-8-jdk-headless wget git gcc unzip ssh
      - checkout
      - run: git submodule update --init
      - run: sudo make test

workflows:
  version: 2
  build-master:
    jobs:
      - build
